version: "3.9"
services:
  smtprelay:
    env_file:
      - aws_ses_secret.env
    image: blueimp/aws-smtp-relay
    command: -h $SMTP_RELAY_GIVEN_HOST -a :$SMTP_RELAY_PORT
    networks:
      - default
    restart: always


  voteit:
    container_name: voteit
    build:
      context: .
    image: vkvoteit:latest
    environment: 
      - SMTP_HOST=$SMTP_RELAY_NAME
      - SMTP_PORT=$SMTP_RELAY_PORT
      - SMTP_SENDER=$SMTP_SENDER
    volumes: 
      - voteitlog:/app/var/log
      - zeodb:/app/var/zeo
    ports:
      - 9010:80
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.voteit.rule=Host(`${VOTEIT_HOST_NAME?}`)"
      - "traefik.http.routers.voteit.entrypoints=websecure"
      - "traefik.http.services.voteit.loadbalancer.server.port=80"
      - "traefik.http.routers.voteit.tls.certresolver=leresolver"
      - "traefik.docker.network=portraefik_proxy"

    networks:
      - proxy
      - default
    restart: always

volumes: 
  voteitlog:
  zeodb:

networks:
  proxy:
    external:
      name: portraefik_proxy
