version: "3.9"
services:
  smtprelay:
    image: blueimp/aws-smtp-relay
    env_file:
      - smtprelay.env
    ports:
      - 1025:1025
    command: -h ${{SMTP_RELAY_HOST}}
    networks:
      - default
    restart: always


  voteit:
    container_name: voteit
    build:
      context: .
    image: vkvoteit:latest
    env_file:
      - voteit.env

    volumes: 
      - voteitlog:/app/var/log
      - zeodb:/app/var/zeo
    ports:
      - 9010:80
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.voteit.rule=Host(`${{HOST_NAME}}`)"
      - "traefik.http.routers.voteit.entrypoints=websecure"
      - "traefik.http.services.voteit.loadbalancer.server.port=80"
      - "traefik.http.routers.voteit.tls.certresolver=leresolver"
      - "traefik.docker.network=portraefik_proxy"
      #- "traefik.http.routers.voteit.middlewares=authelia@docker"

    networks:
      - proxy
      - default

volumes: 
  voteitlog:
  zeodb:

networks:
  proxy:
    external:
      name: portraefik_proxy